// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObandoGamboaFabricio.Data;

#nullable disable

namespace ObandoGamboaFabricio.Migrations
{
    [DbContext(typeof(appDbContext))]
    [Migration("20250519184054_libros migracion")]
    partial class librosmigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObandoGamboaFabricio.Models.Libro", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLibro"));

                    b.Property<DateOnly>("AnioPublicacion")
                        .HasColumnType("date");

                    b.Property<string>("AutorLibro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneroLibro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreLibro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("pagLibro")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("IdLibro");

                    b.ToTable("Libros", (string)null);
                });

            modelBuilder.Entity("ObandoGamboaFabricio.Models.Personaje", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonaje"));

                    b.Property<string>("ApellidoPersonaje")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EstadoPersonaje")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FecNac")
                        .HasColumnType("date");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<string>("LugNac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombrePersonaje")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("IdPersonaje");

                    b.HasIndex("LibroId");

                    b.HasIndex("RolId");

                    b.ToTable("Personajes", (string)null);
                });

            modelBuilder.Entity("ObandoGamboaFabricio.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("DescripcionRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("ObandoGamboaFabricio.Models.Personaje", b =>
                {
                    b.HasOne("ObandoGamboaFabricio.Models.Libro", "libro")
                        .WithMany("Personaje")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObandoGamboaFabricio.Models.Rol", "rol")
                        .WithMany("personaje")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("libro");

                    b.Navigation("rol");
                });

            modelBuilder.Entity("ObandoGamboaFabricio.Models.Libro", b =>
                {
                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("ObandoGamboaFabricio.Models.Rol", b =>
                {
                    b.Navigation("personaje");
                });
#pragma warning restore 612, 618
        }
    }
}
